Gemfile
The extension integrates and adds Flutterwave as a payment gateway. This provides a wide array of payment methods depending on the customers locale.
Before a customer can checkout, he/she will trigger a flutterwave modal that will provide a way to pay. The checkout will automatically finish the checkout process as soon as payment is confirmed. Final verification of the flutterwave transaction will be done during the concluding stages of the spree payment process.
With respect to the complexity of implementing checkout in the backend with flutterwave, vendors will only be allowed to add flutterwave to the frontend.
Run the migrations
```ruby
bundle exec rails g spree_flutterwave:install
```
- An overview of why the …
=> feat: add flutterwave extension

Gemfile.lock
To avoid installation failure, the lock file has been updated.
=> use updated lock file

.github/workflows/dev-deploy-docker.yml, Gemfile.lock
Bug was caused by rails expecting a certain module to be defined.
=> fix: undefined constant

Dockerfile.development, Gemfile
This is caused by `spree_gateway` overriding changes we made to ``update_from_params`. Rearranging the dependencies solves the issue.
=> Fix: Payment Source Not being set

.github/workflows/dev-deploy-docker.yml, Gemfile.lock
use `CURRENCY_CONVERTER_API_KEY` instead of `CURRENCY_CONVERTER_API`
=> feat: use new env var

Dockerfile.production, Gemfile, Gemfile.lock
=> chore: bump spree_fx_currency version

Gemfile, Gemfile.lock
=> chore: bump spree_fx_currency to v4.0.4

Gemfile, Gemfile.lock
=> chore: bump spree_fx_currency version to v4.0.5

Gemfile, Gemfile.lock
=> chore: bump spree_fx_currency to v4.0.6

app/controllers/spree/api/V2/platform/cms_sections_controller.rb
=> fix: upload of cms section images via API v2

Gemfile, Gemfile.lock
update flutterwave to handle duplicate flutterwave payment methods
=> bug fix: Payments source can't be blank

Gemfile, Gemfile.lock
remove `jsonb` and replace with `json`
=> remove problematic migrations

Gemfile, Gemfile.lock
accommodate already existing clumns
=> feat: `if_not_exists: true`

Gemfile, Gemfile.lock
So that the correct public key is chosen and injected into the javascript files
=> fix: choose correct flutterwave payment method during checkout

Gemfile, Gemfile.lock
=> chore: bump spree-clone-store to v1.1.3

Gemfile, Gemfile.lock
=> dep: bump spree-clone store to v1.1.4

Gemfile, Gemfile.lock
=> dep: bump spree_fx_currency to v4.0.7

Gemfile, Gemfile.lock
The new version fixes a bug where customers couldn't change to a different payment method once they made their first selection.
=> build: bump flutterwave gateway version

app/overrides/spree/api/V2/platform/products_controller_decorator.rb
Apply fix from https://github.com/spree/spree/pull/11793/files
=> fix product api

Gemfile.lock
use latest version of `spree_multi_vendor`
=> build: update to use latest `spree_multi_vendor`

Gemfile, Gemfile.lock
=> build: update flutterwave to `v0.0.8`

app/controllers/spree/api/V2/platform/stores_controller.rb
Add endpoint for stores to facilitate CRUD operations on stores
=> feat: add missing stores endpoint for v2

Gemfile, Gemfile.lock
=> build: update `spree_clone_store`

app/controllers/spree/api/V2/platform/products_controller_decorator.rb
The previous implementation didn't work in production. The new implementation works both in production and development mode.
=> fix: handle when an array is passed in as a parameter

Gemfile, Gemfile.lock
=> build: update spree_flutterwave

app/controllers/spree/api/V2/platform/shipping_methods_controller_decorator.rb, app/serializers/spree/api/v2/platform/shipping_method_serializer_decorator.rb
- Add zones to serialiser in order to load zones
- Add zone to permitted params list
=> feat: add zones to shipping methods

Gemfile, Gemfile.lock
=> build: bump `spree_clone_store` to 1.1.7

Gemfile, Gemfile.lock
Fixes a bug in cloning stock where the master variants where being ignored. This update fixes that issue.
=> build: update `spree_clone_store` to 1.1.8

app/views/spree/shared/_footer.html.erb, app/views/spree/shared/_whatsapp.html.erb
Add floating WhatsApp chat
only opens when a contact phone number is set
=> feat: add chat of whatsapp button

Gemfile.lock
=> deps: bump spree-autologin commit hash
